checking connection to api in test

diff --git a/CDDBAPI/Jenkinsfile b/CDDBAPI/Jenkinsfile
--- a/CDDBAPI/Jenkinsfile
+++ b/CDDBAPI/Jenkinsfile
@@ -135,20 +135,23 @@ DBSRV=cddb:3306" >denv/.env
             testfail=0
             echo "Doing some tests"
             # Get API port for testing
-            counter=0
+            docker ps -a | grep registry-int
+            apiport=`docker port devapi-v\${BUILD_NUMBER} | grep '8080/tcp' | sed 's/^.*://'`
+            apiip=`docker inspect devapi-v\${BUILD_NUMBER} | grep IPAddress | tail -1 | awk '{print \$2}' | sed 's/[",]//g'`
+
             # Allow time for container to start
+            counter=0
             while ! curl \${apiip}:\${apiport} 2>/dev/null | grep Hello  >/dev/null 2>&1
             do
               sleep 5
               counter=`expr \$counter + 1`
               if [ "${counter}" -gt "12" ]
               then
-                break
+                echo "Failed to connect to API in a timely fashion"
+                exit 1
               fi
             done
-            docker ps -a | grep registry-int
-            apiport=`docker port devapi-v\${BUILD_NUMBER} | grep '8080/tcp' | sed 's/^.*://'`
-            apiip=`docker inspect devapi-v\${BUILD_NUMBER} | grep IPAddress | tail -1 | awk '{print \$2}' | sed 's/[",]//g'`
+
             if curl \${apiip}:\${apiport} 2>/dev/null | grep Hello  >/dev/null 2>&1
             then
               echo "[PASS] Top URL"
